CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y

CONFIG_PMW3610=y
CONFIG_PMW3610_FORCE_AWAKE=y
CONFIG_PMW3610_CPI=1000
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_Y=y

#CONFIG_PMW3610_LOG_LEVEL_DBG=y
#
# Bump the power up
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Help Realtek and Intel chips a bit
CONFIG_BT_CTLR_PHY_2M=n
