CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=n
CONFIG_PMW3610=y
CONFIG_PMW3610_FORCE_AWAKE=y
CONFIG_PMW3610_CPI=200
CONFIG_PMW3610_ORIENTATION_90=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=y

# CONFIG_PMW3610_LOG_LEVEL_DBG=y
